spring:
  application:
    name: PickPayDesafio

  datasource:
    url: jdbc:postgresql://localhost:5432/desafioPickPay
    username: postgres
    password: 0814jw
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

autorizacao:
  url: https://util.devi.tools/api/v2/authorize


notificacao:
  url: https://util.devi.tools/api/v1/notify